// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5505.ArTiJaBr.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5505.ArTiJaBr.Robot;

/**
 *
 */
public class driveStraight extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    double Speed;
    double Distance;
    boolean isDone;
    double startDistance;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public driveStraight(double speed, double distance) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    Speed = speed;
    Distance = distance;
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        Robot.driveTrain.isDriverControlMode = false;
        startDistance = Robot.driveTrain.getLeftEncoder();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        if (Distance - (Robot.driveTrain.getLeftEncoder() - startDistance) > 30) {
            Robot.driveTrain.driveStraight(Speed);
            isDone = false;
        } else if (Distance - (Robot.driveTrain.getLeftEncoder() - startDistance) < 30) {
            Robot.driveTrain.driveStraight(-Speed);
            isDone = false;
        } else {
            Robot.driveTrain.stop();
            isDone = true;
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return isDone || Robot.driveTrain.isDriverControlMode;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.driveTrain.stop();
        Robot.driveTrain.isDriverControlMode = true;
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
